1:
  led_pin : 16
  pir_pin : 19

2:
  led_pin : 21
  pir_pin : 20

3:
  led_pin : 13
  pir_pin : 12

4:
  led_pin : 5
  pir_pin : 6

5:
  led_pin : 25
  pir_pin : 24

6:
  led_pin : 22
  pir_pin : 23
